/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as LayoutImport } from './routes/_layout'
import { Route as IndexImport } from './routes/index'
import { Route as LayoutUserIndexImport } from './routes/_layout/user/index'
import { Route as LayoutPersonIndexImport } from './routes/_layout/person/index'
import { Route as LayoutPersonCreateImport } from './routes/_layout/person/create'
import { Route as LayoutUserUserIdIndexImport } from './routes/_layout/user/$userId/index'
import { Route as LayoutPersonPersonIdIndexImport } from './routes/_layout/person/$personId/index'
import { Route as LayoutPersonPersonIdEditImport } from './routes/_layout/person/$personId/edit'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const LayoutUserIndexRoute = LayoutUserIndexImport.update({
  id: '/user/',
  path: '/user/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutPersonIndexRoute = LayoutPersonIndexImport.update({
  id: '/person/',
  path: '/person/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutPersonCreateRoute = LayoutPersonCreateImport.update({
  id: '/person/create',
  path: '/person/create',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutUserUserIdIndexRoute = LayoutUserUserIdIndexImport.update({
  id: '/user/$userId/',
  path: '/user/$userId/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutPersonPersonIdIndexRoute = LayoutPersonPersonIdIndexImport.update({
  id: '/person/$personId/',
  path: '/person/$personId/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutPersonPersonIdEditRoute = LayoutPersonPersonIdEditImport.update({
  id: '/person/$personId/edit',
  path: '/person/$personId/edit',
  getParentRoute: () => LayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_layout/person/create': {
      id: '/_layout/person/create'
      path: '/person/create'
      fullPath: '/person/create'
      preLoaderRoute: typeof LayoutPersonCreateImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/person/': {
      id: '/_layout/person/'
      path: '/person'
      fullPath: '/person'
      preLoaderRoute: typeof LayoutPersonIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/user/': {
      id: '/_layout/user/'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof LayoutUserIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/person/$personId/edit': {
      id: '/_layout/person/$personId/edit'
      path: '/person/$personId/edit'
      fullPath: '/person/$personId/edit'
      preLoaderRoute: typeof LayoutPersonPersonIdEditImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/person/$personId/': {
      id: '/_layout/person/$personId/'
      path: '/person/$personId'
      fullPath: '/person/$personId'
      preLoaderRoute: typeof LayoutPersonPersonIdIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/user/$userId/': {
      id: '/_layout/user/$userId/'
      path: '/user/$userId'
      fullPath: '/user/$userId'
      preLoaderRoute: typeof LayoutUserUserIdIndexImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

interface LayoutRouteChildren {
  LayoutPersonCreateRoute: typeof LayoutPersonCreateRoute
  LayoutPersonIndexRoute: typeof LayoutPersonIndexRoute
  LayoutUserIndexRoute: typeof LayoutUserIndexRoute
  LayoutPersonPersonIdEditRoute: typeof LayoutPersonPersonIdEditRoute
  LayoutPersonPersonIdIndexRoute: typeof LayoutPersonPersonIdIndexRoute
  LayoutUserUserIdIndexRoute: typeof LayoutUserUserIdIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutPersonCreateRoute: LayoutPersonCreateRoute,
  LayoutPersonIndexRoute: LayoutPersonIndexRoute,
  LayoutUserIndexRoute: LayoutUserIndexRoute,
  LayoutPersonPersonIdEditRoute: LayoutPersonPersonIdEditRoute,
  LayoutPersonPersonIdIndexRoute: LayoutPersonPersonIdIndexRoute,
  LayoutUserUserIdIndexRoute: LayoutUserUserIdIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/person/create': typeof LayoutPersonCreateRoute
  '/person': typeof LayoutPersonIndexRoute
  '/user': typeof LayoutUserIndexRoute
  '/person/$personId/edit': typeof LayoutPersonPersonIdEditRoute
  '/person/$personId': typeof LayoutPersonPersonIdIndexRoute
  '/user/$userId': typeof LayoutUserUserIdIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/person/create': typeof LayoutPersonCreateRoute
  '/person': typeof LayoutPersonIndexRoute
  '/user': typeof LayoutUserIndexRoute
  '/person/$personId/edit': typeof LayoutPersonPersonIdEditRoute
  '/person/$personId': typeof LayoutPersonPersonIdIndexRoute
  '/user/$userId': typeof LayoutUserUserIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/_layout/person/create': typeof LayoutPersonCreateRoute
  '/_layout/person/': typeof LayoutPersonIndexRoute
  '/_layout/user/': typeof LayoutUserIndexRoute
  '/_layout/person/$personId/edit': typeof LayoutPersonPersonIdEditRoute
  '/_layout/person/$personId/': typeof LayoutPersonPersonIdIndexRoute
  '/_layout/user/$userId/': typeof LayoutUserUserIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/login'
    | '/person/create'
    | '/person'
    | '/user'
    | '/person/$personId/edit'
    | '/person/$personId'
    | '/user/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/login'
    | '/person/create'
    | '/person'
    | '/user'
    | '/person/$personId/edit'
    | '/person/$personId'
    | '/user/$userId'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/login'
    | '/_layout/person/create'
    | '/_layout/person/'
    | '/_layout/user/'
    | '/_layout/person/$personId/edit'
    | '/_layout/person/$personId/'
    | '/_layout/user/$userId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_layout",
        "/login"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/person/create",
        "/_layout/person/",
        "/_layout/user/",
        "/_layout/person/$personId/edit",
        "/_layout/person/$personId/",
        "/_layout/user/$userId/"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/_layout/person/create": {
      "filePath": "_layout/person/create.tsx",
      "parent": "/_layout"
    },
    "/_layout/person/": {
      "filePath": "_layout/person/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/user/": {
      "filePath": "_layout/user/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/person/$personId/edit": {
      "filePath": "_layout/person/$personId/edit.tsx",
      "parent": "/_layout"
    },
    "/_layout/person/$personId/": {
      "filePath": "_layout/person/$personId/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/user/$userId/": {
      "filePath": "_layout/user/$userId/index.tsx",
      "parent": "/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
